#!/usr/bin/env node
// Validate the shape of a produced G-code file. Catches regressions where
// orc_slice returns 0 but produces malformed or truncated output.
//
// Checks:
//   1. file size within an expected band
//   2. has the Orca header / config block markers
//   3. contains layer-change markers + extrusion moves
//   4. ends with the filament/time footer near EOF
//   5. no null bytes (would indicate the std::string -> buffer copy was
//      truncated mid-binary-zone)
//
// Each check prints `PASS check_name` or `FAIL check_name <detail>`.
// Exits 0 if all checks pass, 1 if any fail.

const fs = require('fs');

const inPath = process.argv[2] || '/tmp/orca-wasm-test.gcode';
if (!fs.existsSync(inPath)) {
  console.error(`FAIL: file not found ${inPath}`);
  process.exit(1);
}

const gcode = fs.readFileSync(inPath, 'utf8');
let failures = 0;

function check(name, ok, detail = '') {
  if (ok) {
    console.log(`PASS ${name}`);
  } else {
    console.log(`FAIL ${name} ${detail}`);
    failures++;
  }
}

// 1. Size band. Reference baseline for cylinder.stl + default config is
// ~880 KB. Allow 500 KB – 5 MB to absorb upstream tweaks without
// triggering false positives.
const sizeKB = gcode.length / 1024;
check('size_range',
  sizeKB >= 500 && sizeKB <= 5000,
  `got ${sizeKB.toFixed(1)} KB (expected 500–5000)`);

// 2. Orca header block. Orca v2.3.x stamps `; HEADER_BLOCK_START` as the
// very first line and follows it with `; generated by OrcaSlicer X.Y.Z`.
check('header_present',
  /^; HEADER_BLOCK_START/.test(gcode) && /; generated by OrcaSlicer/.test(gcode.slice(0, 1024)),
  `first line was: ${gcode.split('\n', 1)[0]}`);

// 3. Layer-change markers. Orca emits `;LAYER_CHANGE` (no space) per layer;
// cylinder.stl @ 0.2 mm layer height is ~125 layers.
const layerChanges = (gcode.match(/^;LAYER_CHANGE$/gm) || []).length;
check('layer_changes',
  layerChanges >= 50 && layerChanges <= 500,
  `got ${layerChanges} (expected 50–500)`);

// 4. Extrusion moves — G1 X… Y… E… moves are the bulk of any real slice.
const g1Extrusions = (gcode.match(/^G1 .*E[\d.\-]+/gm) || []).length;
check('extrusion_moves',
  g1Extrusions >= 1000,
  `got ${g1Extrusions} (expected ≥ 1000)`);

// 5. Filament/time footer — Orca writes a stats block (filament used,
// estimated printing time) after EXECUTABLE_BLOCK_END.
check('stats_footer',
  /; filament used \[mm\]/.test(gcode) && /; estimated printing time/.test(gcode),
  'missing filament-used / printing-time summary lines');

// 6. Config block trailer — Orca writes a `; CONFIG_BLOCK_END` line as
// the last meaningful content. Catches truncation regressions in the
// bridge's std::string -> buffer copy.
check('config_block_end',
  /; CONFIG_BLOCK_END\s*$/.test(gcode.trimEnd()),
  'missing "; CONFIG_BLOCK_END" trailer');

// 6. No null bytes / binary junk.
const nulCount = (gcode.match(/\0/g) || []).length;
check('no_null_bytes',
  nulCount === 0,
  `found ${nulCount} NUL bytes`);

console.log(`---`);
console.log(failures === 0 ? 'PASS overall' : `FAIL overall (${failures} check(s) failed)`);
process.exit(failures === 0 ? 0 : 1);
