# Boost from the shared wasm-deps prefix (built threading=single, Wasm EH).
# Boost.Thread is not built (single-threaded); `thread` resolves to the
# header-only single-thread shim in wasm_shims/boost_runtime (nothing linked,
# so no ABI overlap with a real libboost_thread).
if(NOT WASM_DEPS_PREFIX)
  message(FATAL_ERROR "WASM_DEPS_PREFIX not set")
endif()
set(_blib "${WASM_DEPS_PREFIX}/lib")
file(GLOB _bver_dirs "${WASM_DEPS_PREFIX}/include/boost/version.hpp")
if(NOT _bver_dirs)
  message(FATAL_ERROR "Boost headers missing in ${WASM_DEPS_PREFIX}/include")
endif()
set(Boost_FOUND TRUE)
set(Boost_VERSION 108400)
set(Boost_VERSION_STRING "1.84.0")
set(Boost_INCLUDE_DIR "${WASM_DEPS_PREFIX}/include")
set(Boost_INCLUDE_DIRS "${WASM_DEPS_PREFIX}/include")
set(Boost_LIBRARIES "")
if(NOT TARGET Boost::headers)
  add_library(Boost::headers INTERFACE IMPORTED GLOBAL)
  set_target_properties(Boost::headers PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${WASM_DEPS_PREFIX}/include"
    INTERFACE_COMPILE_DEFINITIONS "BOOST_LOG_NO_THREADS;BOOST_LOG_STATIC_LINK;BOOST_ALL_NO_LIB;BOOST_NO_CXX98_FUNCTION_BASE")
  add_library(Boost::boost ALIAS Boost::headers)
endif()
foreach(_c system filesystem regex chrono date_time iostreams program_options log log_setup)
  string(TOUPPER ${_c} _C)
  set(_p "${_blib}/libboost_${_c}.a")
  if(EXISTS "${_p}")
    set(Boost_${_C}_FOUND TRUE)
    set(Boost_${_C}_LIBRARY "${_p}")
    list(APPEND Boost_LIBRARIES "${_p}")
    if(NOT TARGET Boost::${_c})
      add_library(Boost::${_c} STATIC IMPORTED GLOBAL)
      set_target_properties(Boost::${_c} PROPERTIES IMPORTED_LOCATION "${_p}" INTERFACE_LINK_LIBRARIES Boost::headers)
    endif()
  else()
    set(Boost_${_C}_FOUND FALSE)
  endif()
endforeach()
# log depends on these; order matters for static linking.
list(APPEND Boost_LIBRARIES "${_blib}/libboost_filesystem.a" "${_blib}/libboost_regex.a"
                            "${_blib}/libboost_date_time.a" "${_blib}/libboost_system.a")
foreach(_h thread nowide atomic locale)
  string(TOUPPER ${_h} _H)
  set(Boost_${_H}_FOUND TRUE)
  if(NOT TARGET Boost::${_h})
    add_library(Boost::${_h} INTERFACE IMPORTED GLOBAL)
    set_target_properties(Boost::${_h} PROPERTIES INTERFACE_LINK_LIBRARIES Boost::headers)
  endif()
endforeach()
if(EXISTS "${_blib}/libboost_nowide.a")
  list(APPEND Boost_LIBRARIES "${_blib}/libboost_nowide.a")
endif()
